### ISSUE TITLE
Targets - last element not checked?

### ISSUE THREAD

**Issue by replay111** [czerwonk/ping_exporter#125]
Hi - I have configuration similar to this:

```
targets:
  - 10.0.0.1
  - 10.0.0.2
  - 10.0.0.3
```

I was playing with grafana and alerts and I have noticed that if I block last adres (10.0.0.3 in this case) - from docker container pings are blocked, but ping_exporter shows ping_loss_ratio as 0 (zero), so according to ping_exporter IP address is available.

But when I add some additional addres like this:
```
targets:
  - 10.0.0.1
  - 10.0.0.2
  - 10.0.0.3
  - 10.0.0.4
 ```
ping_exporter now works fine with .3 address but is totally ignoring .4 address...

Does anyone have/had some similar behavior?
I am using:
VERSION="1.1.3"
PLATFORM="linux"
ARCH="amd64"

**Comment by gogglespisano** [comment]
Do you have a newline after the last entry?  Maybe it's ignored if a newline is missing.

**Comment by replay111** [comment]
I will close this one - as I suspect that my firewall was tricking me. I think the connection estabilished and another rule was allowing for passing. I will take a closer look on that, as I am not sure if this is a problem of ping_exporter or my lack of knowledge with firewalls ;-)
