### ISSUE TITLE
metric type (avg, best, ...) as label

### ISSUE THREAD

**Issue by czerwonk** [czerwonk/ping_exporter#2]
https://twitter.com/goebelmeier/status/974269206454816768

**Comment by brian-brazil** [comment]
You have misintrepreted the guidelines. These should remain as separate metrics, as they cannot be summed or averaged meaningfully. It's also usual to use seconds rather than milliseconds.

**Comment by czerwonk** [comment]
Hi Brian,

you are right. I restored the correct metric names and deprecated the wrong (newly introduced) one. We will remove the wrong metric name in a future release. Thanks for the clarification.

Cheers,
Daniel
