### ISSUE TITLE
socket: permission denied

### ISSUE THREAD

**Issue by sachaz** [czerwonk/ping_exporter#23]
Hi,

```
$uname -prsv
OpenBSD 6.5 GENERIC.MP#5 amd64
```

When I'm launching ping_exporter with an user I got:

```
$/usr/local/bin/ping_exporter --web.listen-address=0.0.0.0:9101 --config.path=/etc/ping_exporter.conf
ERRO[0000] listen ip4:icmp 0.0.0.0: socket: permission denied  source="main.go:97"
```
the same user can:

- use ping

```
$ping x.org  
PING x.org (131.252.210.176): 56 data bytes
64 bytes from 131.252.210.176: icmp_seq=0 ttl=46 time=157.838 ms
```

 - launch node_exporter.

**Comment by ashleyprimo** [comment]
That's likely because `ping` has suid privileges; your own user does not have prerequisite permission to perform a privileged action.

**Comment by sachaz** [comment]
The ping is done with the same user as used to launch the daemon :o

**Comment by ashleyprimo** [comment]
@sachaz Please lookup [SUID](https://www.linux.com/tutorials/what-suid-and-how-set-suid-linuxunix/), and http://man7.org/linux/man-pages/man8/getcap.8.html - this is not an issue with the exporter. 

PING often has SUID set, or on a modern Linux system, it'll likely to have "capabilities" set - which ws where `getcap` comes in.

Example:
```
$ getcap $(which ping) 
/usr/bin/ping = cap_net_raw+ep
```

**Comment by NikNikM** [comment]
@sachaz I had the same problem and as @ashleyprimo said, the problem is related to SUID.
You can solve it with:
setcap cap_net_raw=+ep /path-to-your-exporter/ping_exporter
(not /bin/ping and in your case: /usr/local/bin/ping_exporter)
or if you are using Ansible:
- name: Set cap_net_raw=+ep
  capabilities:
    path: "{{ pe_install_dir }}/{{ pe_file_name }}"
    capability: cap_net_raw=+ep
    state: present

**Comment by sachaz** [comment]
Thanks a lot for your answers !
