### ISSUE TITLE
Github releases?

### ISSUE THREAD

**Issue by nhinds** [czerwonk/ping_exporter#3]
Could binaries for this exporter please be released on github, similar to what others do for e.g. [node_exporter](https://github.com/prometheus/node_exporter/releases/tag/v0.15.2), [process_exporter](https://github.com/ncabatoff/process-exporter/releases)?

Binary releases are handy to avoid having to compile the exporter on each machine with `go get`, for people who don't wish to run it inside a docker container.

**Comment by czerwonk** [comment]
v.0.4.4 was cross compiled using gox, so it's available pre-compiled for the common platforms
