### ISSUE TITLE
Release of new version (Prebuild binaries)

### ISSUE THREAD

**Issue by LKaemmerling** [czerwonk/ping_exporter#38]
Hey @czerwonk, first of all, thank you for that great exporter! 

Would it be possible that you release the latest changes from your master branch as prebuild binaries, as you did it with v0.4.4? Currently, the changes are only available within the docker container (with tag: latest), using docker is not possible within my current environment.

Thank you!

**Comment by czerwonk** [comment]
Hi, thanks for your feedback. I just released the current code as 0.4.5 with prebuild binaries

**Comment by LKaemmerling** [comment]
@czerwonk thank you! You could also "automate" this by using https://github.com/goreleaser/goreleaser and github actions :) Than it should be easier for you.
