### ISSUE TITLE
Can we get a new build?

### ISSUE THREAD

**Issue by foogod** [czerwonk/ping_exporter#58]
It looks like the most recent release version was from back in March, but there have been a number of updates to the git repo since then.  In particular, there is 943e338f which fixes the completely broken metric names, but is not present in the latest 0.4.7 release (making it a poor choice for anybody to actually use, IMHO).

**Comment by nhjjreuter** [comment]
Can this new build include a name change for `ping_loss_percent` to `ping_loss_ratio` as mentioned in #22 to consolidate metric name changes?

**Comment by czerwonk** [comment]
Totally agree. I will trigger a new build today

**Comment by aqw** [comment]
It looks like 0.4.8 has been tagged and built. So in that sense, this is done.

However, if I may suggest: I agree with @nhjjreuter that changing the metric names all at once makes sense. Perhaps it would be good to address #22 (and perhaps also #60) and then bump the version to signify the breaking changes (to `0.5.0` or `1.0.0`).

Thoughts?

**Comment by foogod** [comment]
That sounds like a good idea to me too, though I'd also say if we're going to be making breaking changes, I'd suggest also changing the units to report seconds by default (so that you need to use the command line option if you still want ms, instead of the other way around).  That way the whole thing is fully consistent with Prometheus best practices by default..

So maybe change the metric name to `packet_loss_ratio`, change the default to seconds, address the bug in #60, and then put out the result as `1.0.0` (to make it clear it's changing a bunch of stuff people might be relying on)?

(I would also say that if we're making a major version bump it would be nice to get PR #59 included as well, but that's currently blocked on upstream changes anyway, so I'm not sure it should hold up everything else..)

Since I've been hacking on this stuff recently anyway, I can put together a quick PR for all of the above, if you want.
