### ISSUE TITLE
A semi-random subset of metrics can be returned for any given scrape

### ISSUE THREAD

**Issue by nhinds** [czerwonk/ping_exporter#7]
When configured to scrape a large-enough number of targets, the metrics provided by this exporter do not consistently include all configured targets.

I am running with 68 targets, half of which are unreachable (will timeout) and half of which have varying ping times. The commandline is approximately `ping_exporter -ping.interval 1m -ping.timeout 10s <first ip> <second ip> ...`.

Running `curl http://localhost:9427/metrics` every few seconds returns different subsets of my monitored IPs. The first few `curl`s might return all of the IPs which responded quickly, the next few `curl`s might return the IPs which were slower to respond, and the next few `curl`s might return all of the IPs which timed out.

```
# Scrape the server running the ping exporter every 2s, counting the number of ping_rtt_worst_ms lines:
$ for i in {1..30}; do curl -s server:9427/metrics|grep ping_rtt_worst_ms | wc -l; sleep 2; done
19
9
9
9
9
39
39
39
39
39
39
39
39
39
39
39
39
39
39
39
39
39
39
39
39
39
39
26
26
26
```

It seems like the same data is returned for a few requests in a row, then something changes and different data is returned (which does not include the same IPs as the previous requests). This is consistent with [collector.go](https://github.com/czerwonk/ping_exporter/blob/master/collector.go#L42-L46) which seems to delete all information about previously-known ping statistics whenever there are results.

In real-world terms, I've got a HA Prometheus setup with multiple Prometheus instances scraping the same ping_exporter instances. Usually exporters return consistent data for consecutive scrapes, but this behaviour of clearing old data means that the different Prometheus instances each see a different subset of the data, and do not agree on alerting.

**Comment by corny** [comment]
By design the exporter clears all results by calling `ExportAndClear()`. Your scrape interval should be larger then the `ping interval + timeout` to receive a set of all monitored IPs. This design does not work well if you are using more than one scraper.

Please describe your expected behavour more precisely. What results of which time frame do you expect to be returned?

**Comment by corny** [comment]
Quite easy to implement is to limit the number of results per monitored target. Newer results will overwrite older results. Does that fit your requirements?

**Comment by nhinds** [comment]
> This design does not work well if you are using more than one scraper.

Hmm. My deployment follows the Prometheus [recommendations for making Prometheus highly available](https://prometheus.io/docs/introduction/faq/#can-prometheus-be-made-highly-available?), which is to run multiple Prometheus instances configured to scrape the same targets. I can see how the current design doesn't quite work with that.

> Please describe your expected behavour more precisely. What results of which time frame do you expect to be returned?

I would expect the results of at least one ping to be included per target (at least that way an alert based off `ping_loss_percent` could detect unreachable targets consistently)... I'm using this exporter to ping every 1m, and using Prometheus aggregations to get the max/min/avg/etc. across a longer period of time, so personally I do not need a larger time frame than "the last ping", but for other users I guess there's currently no way to guess what time frame they want other than the time since they last hit the `/metrics` endpoint.

> Quite easy to implement is to limit the number of results per monitored target. Newer results will overwrite older results. Does that fit your requirements?

Do you mean that each monitored target would return data from the last N pings of that target? That would definitely solve what I'm trying to do, and means the exporter doesn't have to "guess" what time frame to return the results from when it's hit.

**Comment by corny** [comment]
Please check out my branch.

**Comment by nhinds** [comment]
Your branch returns consistent results when polling `/metrics` once each target has been pinged at least once, looks good to me :+1:

**Comment by nhinds** [comment]
#9 is merged, this is solved. Thank you :)
