### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by EliasBoulharts** [czerwonk/ping_exporter#78]
I would like to add labels to my addresses.

**Comment by andreasmarkussen** [comment]
I am right there with you :) 

e.g 

targets:
 - google_primary:
     hostname: 8.8.8.8
     tags: ["type":"DNS", "owner":"google"]
  - 8.8.8.8
  - 8.8.4.4
  - 2001:4860:4860::8888
  - 2001:4860:4860::8844
  - google.com

But the format does not matter. Will auto-generate it anyways.
