### ISSUE TITLE
config.yaml file parsing error

### ISSUE THREAD

**Issue by ottobaer** [czerwonk/ping_exporter#86]
I just had to restart the host the ping_exporter runs on and now it won't start. 

`ping_exporter --config.path=/etc/ping_exporter/config.yml`

```
INFO[0000]github.com/czerwonk/ping_exporter/main.go:78 main.main() rtt units: 2                                 
ping_exporter: error: could not load config.path: failed to decode YAML: yaml: unmarshal errors:
  line 6: cannot unmarshal !!map into string
usage: ping_exporter [<flags>] [<targets>...]

```

Here is the config.yaml - it's basically just the example given. 

```
targets:
  - 8.8.8.8
  - 8.8.4.4
  - 2001:4860:4860::8888
  - 2001:4860:4860::8844
  - google.com:
      asn: 15169

dns:
  refresh: 2m15s
  nameserver: 1.1.1.1

ping:
  interval: 15s
  timeout: 3s
  history-size: 42 
  size: 120

options:
  disableIPv6: false
```

**Comment by ottobaer** [comment]
If I remove : 

```
  - google.com:
      asn: 15169
```
it works again - strange.

**Comment by AliDev0ps** [comment]
Version `1.0.1` doesn't support adding custom tags, and the author hasn't released a new version, so you'll need to compile it yourself to use this feature.

**Comment by czerwonk** [comment]
Release for 1.1.0 including this change was issued a few moments ago, so Binaries and Images should be available in a few minutes.
